# coding: utf-8

"""
    Library System API

    API для управління книгами та авторами в бібліотеці.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_authors_get(self) -> None:
        """Test case for authors_get

        Отримати список усіх авторів
        """
        pass

    def test_authors_id_delete(self) -> None:
        """Test case for authors_id_delete

        Видалити автора
        """
        pass

    def test_authors_id_get(self) -> None:
        """Test case for authors_id_get

        Отримати деталі конкретного автора
        """
        pass

    def test_authors_id_put(self) -> None:
        """Test case for authors_id_put

        Оновити інформацію про автора
        """
        pass

    def test_authors_post(self) -> None:
        """Test case for authors_post

        Створити нового автора
        """
        pass

    def test_books_get(self) -> None:
        """Test case for books_get

        Отримати список усіх книг
        """
        pass

    def test_books_id_delete(self) -> None:
        """Test case for books_id_delete

        Видалити книгу
        """
        pass

    def test_books_id_get(self) -> None:
        """Test case for books_id_get

        Отримати деталі конкретної книги
        """
        pass

    def test_books_id_put(self) -> None:
        """Test case for books_id_put

        Оновити інформацію про книгу
        """
        pass

    def test_books_post(self) -> None:
        """Test case for books_post

        Створити нову книгу
        """
        pass


if __name__ == '__main__':
    unittest.main()
