# coding: utf-8

# flake8: noqa
"""
    Library System API

    API для управління книгами та авторами в бібліотеці.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.author import Author
from openapi_client.models.book import Book
